### ISSUE TITLE
maxPartSize const error

### ISSUE THREAD

**Issue by amimimor** [apoorvam/aws-s3-multipart-upload#1]
First, thanks for sharing your code it was really helpful!
It appears to cause an "EntityTooSmall" error from S3. As currently stated in [AWS docs](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html) the minimum part size is 5MB except for the last part. 
In the implementation now maxPartSize is set to `int64(512 * 10000)`, whereas it should be `int64(5 * 1024 * 1024)`
Replacing the const value to the one I wrote here solved the problem

**Comment by thelebdev** [comment]
@apoorvam are you still maintaining this repo or would you like me to fork it and apply @amimimor 's issue?

**Comment by apoorvam** [comment]
@christopheelkhoury I do maintain this repository, somehow had missed this notification earlier. I'll make this change now, but I'm happy to accept PRs if anyone wants to contribute.

**Comment by thelebdev** [comment]
@apoorvam if you like I could submit a PR first thing tomorrow

**Comment by apoorvam** [comment]
@christopheelkhoury Thats great, but I just made that commit. So good for now.

Closing this issue now. If anything, please feel free to open one. Thanks @amimimor @christopheelkhoury
